logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config-rabbitmq:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - rabbitmq

rabbitmq:
  image: rabbitmq:3

  volumes:
    - ./rabbitmq/volume:/var/lib/rabbitmq"
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"

